### ISSUE TITLE
Add `before` action

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#117]
```crystal
class Admin::Users::Index < BaseAction
  before :require_login

  # It should require returning either a LuckyWeb::Response or whatever `continue` returns. Maybe `LuckyWeb::Continue`?
  def require_login
    if logged_in?
      continue
    else
      redirect to: SignIns::New
    end
  end
end
```

**Comment by Xosmond** [comment]
I can't make this works. I have this easy code:

```
class Users::Show < BrowserAction
  before :before_action

  action do
    puts "Base action"
    user = UserQuery.new.find(id)
    render user: user
  end

  def before_action
    puts "before action"
    continue
  end
end

```

Output:
```
10:01:28 web.1      |  Base action
10:01:28 web.1      |  GET /css/app.css? - 200 (552.0µs)
10:01:28 web.1      |  GET /js/app.js? - 200 (1.08ms)
10:01:28 web.1      |  GET /users/1? - 200 (20.57ms)
10:01:28 web.1      |  GET /js/app.js? - 200 (742.0µs)
10:01:28 web.1      |  GET /css/app.css? - 200 (471.0µs)
```

Did you test the callbacks?

**Comment by paulcsmith** [comment]
Yep it's pretty well tested, but maybe I made a mistake, or there is something about your app that makes it not work? Could you push it up and post a link so I can check it ou?

**Comment by paulcsmith** [comment]
Actually it may be that you are using a symbol. It is expecting a bare word @Xosmond 

If you use a symbol then it will run the symbol. Which will do nothing

```
# It will literally run this:
:before_action

# So you'd want to do `before before_action`
# So that it actually calls the method
before_action
```

**Comment by Xosmond** [comment]
@paulcsmith I have tried both forms and none works. He's link of my repo: https://github.com/Xosmond/crystal_blog

**Comment by paulcsmith** [comment]
@Xosmond I figured out the issue. When you use `get`, `put`, `post`, `put` macros it works: https://github.com/luckyframework/web/blob/master/src/lucky_web/routeable.cr#L6-L22

But when you use `action` or `nested_action` it doesn't because the callbacks aren't run at all: https://github.com/luckyframework/web/blob/master/src/lucky_web/routeable.cr#L29-L39

So I need to add some specs here https://github.com/luckyframework/web/blob/master/spec/lucky_web/action_callbacks_spec.cr that have actions with `action` and `nested_action`. The problem is really that `call` should be implemented with just one macro so that there isn't the danger of having it work differently depending on whether you call `action` or `get/put/post/delete`

If you'd like to work on a PR for this, that'd be great, but if not, then I can tackle this sometime this week. Thanks for reporting!

**Comment by paulcsmith** [comment]
@Xosmond fixed it in this PR: https://github.com/luckyframework/web/pull/195

You can run `shards update` to get the latest version of Lucky. Then this *should* work. Please let me know if does :)

**Comment by Xosmond** [comment]
Great @paulcsmith, I was going to do it but im not as good as you on crystal by now. I'll check.
