### ISSUE TITLE
Discuss: Add `member` and `collection` macros to actions?

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#126]
I would like to encourage RESTful routes, but sometimes this is useful. Maybe these macros should be added? This decision doesn't need to be made now since people that want to do this can still use the `get/put/post/delete` macros to do non RESTful routes.

```crystal
class Files::Archive < BaseAction
  # Same as "files/:id/archive"
  member do
    archive_the_file
  end
end
```

**Comment by sardaukar** [comment]
Whatever the method for having non-RESTful routes, I think they shouldn't become 'second class'. As long as they're as useful as "normal" RESTful routes, any solution will do.

On a side note, what made you not want to have a router?

**Comment by paulcsmith** [comment]
`get/post/put/delete` work for non-RESTful routes. That *might* be enough for people. Since *most* routes can be RESTful. But I'm unsure. Might be something we need to experiment with.

There were a few reasons for not going with a router

1) I hate working with path helpers. It's always a pain to remember the naming conventions
2) I wanted type safe params in actions/controllers.
3) If it can be inferred from the class then it's just one less thing to write
4) Part of the reason for using one class per action was to get type safe params, which also led to not having a router


More explanation:

### 1. Path helpers

Stuff like this

```
resources :users do
  resources :tasks
end

new_users_tasks_path # or whatever it is, isn't that intuitive to me.
```

It's also kind of hard to do since you can't create a module inside a of another class or module with macros. There are workarounds, but it's a bit wonky.

Instead I can generate the `self.route/path` helpers on the class itself which IMO is really easy to remember and work with.

### 2. Type safe params in controller/actions

I wanted to have type safe params

```crystal
class Users::Show < BaseAction
  action do
    UserQuery.new.find(id) # I like that I *know* id is a param that I can get at. It's even nicer when dealing with nested actions.
  end
end
```

I couldn't figure out a way to do this with a separate route definition. And even if I could I kind of like that it's done right there in the controller


### 3. If it can be inferred from the class then it's just one less thing to write

Pretty self-explanatory. It's nice to not even have to write the route at all IMO.

### 4. Part of the reason for using one class per action was to get type safe params, which also led to not having a router

Also pretty self-explanatory. The other reason is that now we can do cool stuff like described in #105

**Comment by joshuaclayton** [comment]
One thing I'd urge you to consider: there's weight to supporting edge-cases and options you (and likely others) won't run into often. My experience with Rails and other web frameworks is routing to REST is 98%+ of what both I do, and what I see on client projects.

Having worked on [Factory Girl](https://github.com/thoughtbot/factory_girl) over a number of years, I think my biggest regret is supporting features I had a hard time understanding need for. I'd encourage you to think about whether you think this is necessary, and if not, promote that opinion and provide examples so others are aware of what's possible with REST.

**Comment by sardaukar** [comment]
@joshuaclayton are you advocating for non-RESTful routes to not even by supported?

**Comment by joshuaclayton** [comment]
@sardaukar perhaps! My experience with apps I write, and apps I see, is that they're not used, or when they're used, it's done so incorrectly. I think it's worth considering omitting them, at least for now, and gathering feedback as to whether they're absolutely necessary.

**Comment by paulcsmith** [comment]
Transferred from Slack:

> I will for sure support non-RESTful routes. It’s already there and sometimes you need pretty URLs for stuff. Like `/my-fancy-landing-page` or something like `/sign_in`

So I think the real discussion is whether to add the more non-RESTful stuff like `member/collection` since vanity URLs and SEO optimized URLs are sometimes necessary

**Comment by eliasjpr** [comment]
@paulcsmith some thoughts on the params. 

I think it would be nice to be able to explicitly define the params that should be available to the action. 

param id : String 

The macro can then define a getter with the correct type. Taking it a little further, maybe add validation.

WDYT?

**Comment by paulcsmith** [comment]
@eliasjpr Right now the params and the getter for the params are automatically generated from the path name. http://luckyframework.org/guides/actions-and-routing.html#path-parameters

The downside for now is that they are always strings, but in practice that is usually fine since LuckyRecord casts the params for you.

I do want to make it so that you can use different types though. I think it would look like this:

```crystal
get "/posts/:slug", slug: Slug do
end

# You'd then have a Slug type that can cast the string param
class Slug
  def self.cast(param : String) : Int32
    # Just return the id part of the slug. E.g. "123-my-cool-title" returns 123
  end
end
```

Does that make sense?

**Comment by paulcsmith** [comment]
Chatted with @eliasjpr in Gitter:

> I would say “Don’t add it now and wait for a demand"
> you will notice that people will start asking which will hint you
> https://gitter.im/luckyframework/Lobby?at=59f12a1181cd9a5d7e9fbea0

I think this is a good point. So I'll close this for now and re-open later if people want it and have reasonable use cases.
