### ISSUE TITLE
Make sure these HTML tags are covered

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#138]
I think we've got most of them, but might want to double check http://htmlreference.io

**Comment by 007lva** [comment]
Hi! Just a question, how can I render [Custom Elements](https://developers.google.com/web/fundamentals/web-components/customelements) in Lucky Pages?

**Comment by paulcsmith** [comment]
Great question @007lva! You would do this in your `BasePage`:

```crystal
generate_tag_methods(method_name: "my_custom_element", tag: "my-custom-element")
```

This will generate a few tag methods for easily working with your custom element. You can see the implementation here: https://github.com/luckyframework/web/blob/master/src/lucky_web/tags/base_tags.cr#L9

**Comment by 007lva** [comment]
Thank you!
