### ISSUE TITLE
Add `p` method to `LuckyWeb::Page` that directs the user to use `pp` or `para`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#143]
There isn't a good reason to use `p` in a web page other than to debug something. So we should add a `p` macro to `LuckyWeb::Page` that accepts any number of arguments and let's the user know they should use `para` if they want a paragraph tag and `pp` if they want to debug. `pp` is better anyway because it also outputs the code that it's printing to standard out. It's super handy!

It would look something like this

```crystal
def p(_arg, **args)
  {% raise <<-ERROR
    `p` is not available on Lucky pages. This is because it's not clear whether you want to print something out or use a `p` HTML tag.
    
    Instead try:
      * The `para` method if you want to use an HTML paragraph.
      * The `pp` method to pretty print information for debugging.
    ERROR 
  %}
end
```

**Comment by 5minpause** [comment]
I would like to take this

**Comment by paulcsmith** [comment]
Great! Thanks @5minpause

**Comment by 5minpause** [comment]
My pleasure. I am just learning about Crystal right now, everything is new to me. But it's a great project to learn and feels exciting.

I was wondering: What's the idea behind defining it as a macro on `LuckyWeb::Page` instead of defining it as a method in `LuckyWeb::BaseTags`?

**Comment by paulcsmith** [comment]
It could probably go in either. I don't think there was a clear choice either way so I went with `BasePage`. I may extract it to its own module at some point that get included on `BasePage`. Something like `LuckyWeb::CompileErrors` or something

**Comment by 5minpause** [comment]
I see. Thanks for clearing that up.

**Comment by paulcsmith** [comment]
You're welcome!
