### ISSUE TITLE
Add HTML select helper

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#151]
For examples see the other form helpers: https://github.com/luckyframework/web/blob/master/src/lucky_web/tags/input_helpers.cr and https://github.com/luckyframework/web/blob/master/src/lucky_web/tags/label_helpers.cr

**Comment by azbshiri** [comment]
I'm working this would you add more detail about how to generate an HTML tag? I reviewed `base_tags.cr` but I think it only generates specified tags, am I wrong?

**Comment by paulcsmith** [comment]
@azbshiri Great questions. There are a couple parts to this. The BaseTags module is included here: https://github.com/luckyframework/web/blob/master/src/lucky_web/page.cr along with a few other modules that are used for building HTML.

Here's a gist of what using the tags should look like: https://gist.github.com/paulcsmith/da92c958379774fd3802c820f3bf98e7

In terms of implementation I'm imaging it would be something like this:

1. Add `select` and `option` to the list of tags in BaseTags if they are not there already.
2. Create a `SelectHelpers` module

```crystal
# src/lucky_web/select_helpers.cr
module SelectHelpers
  # Docs for alias: https://crystal-lang.org/docs/syntax_and_semantics/alias.html
  alias SelectOption = (String | Int32 | Int64)

  def select(field : LuckyRecord::AllowedField, **html_options)
    # This will merge the passed in attributes with the generated name attribute
    select merge_options(html_options, {"name" => input_name(field)}) do
      # Yield the block so you can pass render pages in the select
      yield
    end
  end

  def options_for_select(field : LuckyRecord::AllowedField, select_options : Array(String, SelectOption, **html_options)
    select_options.each do |select_name, select_value|
       is_selected = if select_value.to_s == field.value.to_s
         "true"
       else
          "false"
       end
      option select_name, merge_options(html_options, {"value" => select_value.to_s, "selected" => is_selected})
    end
  end

  private def input_name(field)
    "#{field.form_name}:#{field.name}"
  end
end
```
3. Spec would be tested similar to https://github.com/luckyframework/web/blob/master/spec/lucky_web/link_helpers_spec.cr or https://github.com/luckyframework/web/blob/master/spec/lucky_web/input_helpers_spec.cr

Note that I didn't test those snippets so there may be error or syntax issues, but I hope this points you in the right direction. If you get stuck feel free to open a PR and ask for help. I can comment on the code a directly with suggestions.

Thanks for taking a crack at this!

**Comment by azbshiri** [comment]
@paulcsmith Great details. I was actually created test case, helper file and etc. but I was wondering should I change BaseTag or not. So depend on details you explained every tag should be generated using BaseTag macros and a tag should be included if need. Correct me if I'm wrong.

**Comment by paulcsmith** [comment]
@azbshiri It's hard to tell without seeing the code. Could you open a PR so I could see what you have now? I think `BaseTag` should mostly remain the same, except for the addition of the select and option tags, which would be used by the select helper for generating selects and options for LuckyRecord::Field objects. Does that make sense?

**Comment by azbshiri** [comment]
@paulcsmith for sure. no problem.

**Comment by azbshiri** [comment]
@paulcsmith Leave this to me. I'm off on Thursday and Friday and I'll do it then. I peek up one or two issues each week to challenge myself.

**Comment by paulcsmith** [comment]
@azbshiri That's awesome. Thanks so much :)

**Comment by azbshiri** [comment]
@paulcsmith What do you think about `select` being a keyword?

**Comment by paulcsmith** [comment]
@azbshiri I tried using `select` and searching for it and it doesn't seem to be a keyword to me. Do you have a link to what you mean? If you meant that `select` is a method on Enumerable then I think using `select` is still ok for this feature. I don't think it will be confusing, but if it is we can rename it later.

**Comment by azbshiri** [comment]
I get this error 

```
Syntax error in src/lucky_web/tags/select_helpers.cr:5: unexpected token: merge_options (expecting when, else or end)
```

**Comment by paulcsmith** [comment]
Oh bummer :( 

Let's try this:

* Let's make the method `select_input` instead of `select`. This will match `text_input`, `color_input` etc.
* In the BaseTags module, remove `select` from the main list of tags and let's add a renamed tag for it called so `select_tag` -> generates a `select` HTML tag: https://github.com/luckyframework/web/blob/master/src/lucky_web/tags/base_tags.cr#L3

How does that sound?

**Comment by azbshiri** [comment]
Here's the spec:

```
require "../../spec_helper"

private class TestPage
  include LuckyWeb::Page

  render do
  end
end

class SomeFormWithCompany
  def company_id
    field = LuckyRecord::Field(String).new(
      name: :company_id,
      param: "company_id",
      value: "",
      form_name: "company"
    )
    LuckyRecord::AllowedField.new(field)
  end
end

describe LuckyWeb::SelectHelpers do
  it "renders select" do
    (view.select form.company_id do; end).to_s.should contain <<-HTML
      <select name="company:company_id"></select>
    HTML
  end

  it "renders select with options" do
    view.select form.company_id do
      options_for_select(form.company_id, [{"Volvo", 1}])
    end.to_s.should contain <<-HTML
      <select name="company:company_id">
        <option value="1">Volvo</option>
      </select>
    HTML
  end
end

private def view
  TestPage.new
end

private def form
  SomeFormWithCompany.new
end
```

The error I get is:

```
in spec/lucky_web/select_helpers_spec.cr:31: undefined method 'options_for_select'

      options_for_select(form.company_id, [{"Volvo", 1}])
      ^~~~~~~~~~~~~~~~~~
```

but options_for_select is defined:

```
module LuckyWeb::SelectHelpers
  alias SelectOption = (String | Int32 | Int64)

  def select(field : LuckyRecord::AllowedField, **html_options)
    select_tag merge_options(html_options, {"name" => input_name(field)}) do
      yield
    end
  end

  def options_for_select(field : LuckyRecord::AllowedField, select_options : Array(String, SelectOption), **html_options)
    select_options.each do |select_name, select_value|
       is_selected = if select_value.to_s == field.value.to_s
         "true"
       else
          "false"
       end
      option select_name, merge_options(html_options, {"value" => select_value.to_s, "selected" => is_selected})
    end
  end

  private def input_name(field)
    "#{field.form_name}:#{field.name}"
  end
end
```

**Comment by paulcsmith** [comment]
@azbshiri Could you open up a PR so I can see all the changed code and pull it down to look around? My guess is that you would need to make sure to include the new `LuckyWeb::SelectHelpers` module in `BasePage` https://github.com/luckyframework/web/blob/master/src/lucky_web/page.cr#L4-L12

LMK if that works. If it doesn't feel free to open a PR and I'll take a closer look!

**Comment by azbshiri** [comment]
https://github.com/luckyframework/web/pull/182
