### ISSUE TITLE
Change Action.route to Action.with

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#170]
So you call route helpers like this `link "edit", to: MyAction::Edit.with(id: something.id)`

Another alternative is `MyAction::Edit(id: something.id)` which is sort, but maybe a bit magical? I'm not sure about it, but it is nice that it's so short. EDIT: This won't work: https://github.com/luckyframework/web/issues/170#issuecomment-340450926

See discussion in Gitter https://gitter.im/luckyframework/Lobby?at=59f7126fd6c36fca31b4223c

From @edwardloveall
> I was thinking about routing last night, and it feels a little weird to me that it's link "foo", to: SomeClass OR link "foo", to: SomeClass.route(with_params)
from an API, it's seems inconsistent that I'm linking to either a class, or a or whatever route returns
i see how it works on link internally, but I wonder if it would make more sense for the params version to look like link "foo", to: SomeAction, params: with_params
.route was a bit of a head scratcher when I first saw it
probably because it's not clear to me that the route method would take params (as opposed to a route, or location)
actually, changing route to with_params or params would also solve this

My response:
> I was thinking it was confusing too but couldn’t come up with a good name. I think your suggestion to rename is great. I think params might be confusing because it seems like it would return a params object or something. with_params is super clear but a bit long. Maybe with would be a good middle ground? link to: Topics::Show.with(topic) not quite as clear as with_params, but at least it’s not actively confusing people, and this way it’s not so much to type once you do learn it. Thoughts?

**Comment by edwardloveall** [comment]
Another thought was: `link "edit", to: MyAction::Edit(id: something.id)`

This is a little strange because it looks like `Edit` is a method. Also, I don't know enough crystal to know if that will even work.

**Comment by paulcsmith** [comment]
Just tried it out and it's a syntax error. Doesn't look like that's possible :(

**Comment by edwardloveall** [comment]
That's probably for the best.

**Comment by edwardloveall** [comment]
what about an overloaded `link` helper?

```crystal
link "list", to: MyAction::Index
link "edit", to: MyAction::Edit, id: something.id
```

**Comment by paulcsmith** [comment]
Sadly that won't work because it's not clear if that should be an HTML id attribute or an id for the link. I think it also makes it less clear what's happening. So if you wanted to build your own helper method it would be hard to tell what to do. By keeping it as a class method it makes it clear how you could call it from your own methods if you wanted to. Like in emails or something

**Comment by edwardloveall** [comment]
I think `with` is probably pretty good then. New users will have to look it up to understand what it means, but once you learn it, it's probably pretty easy to remember and use correctly.

**Comment by paulcsmith** [comment]
I agree. It might not make immediate sense, but it's something easy to learn and once you learn it you'll use it all the time and it hopefully won't be an issue :D

**Comment by citizen428** [comment]
I feel `for` could be a good alternative: `Topics::Show.for(topic)` / `MyAction::Edit.for(id: something.id)`. Otherwise I think `with_params` would be better than just `with`, since slightly less typing is less important than semantic clarity, though one could provide aliases.

**Comment by edwardloveall** [comment]
I thought about `for` also. It doesn't feel as good as `with` to me because `for` implies the route is about whatever params you're passing into it, which isn't always the case: `Topic::Show.for(id: topic.id, articles_since: timestamp, random_seed: seed)`. Where are `with` implies data that is coming along _with_ whatever route, which is actually what's happening.

I actually do still like `with_params`. It's extremely clear and I don't think it passes the "too long" threshold.

**Comment by edwardloveall** [comment]
Better example: `Product::Index.for(region: region.id, guest: true, coupon_offer: coupon)`. It's stops really becoming _for_ that product or products because sometimes there are extra things that need to be in whatever view or action you're visiting.

**Comment by citizen428** [comment]
Yeah, I guess we can agree to disagree on `for` 😉 I still think of as "the action *for* a given set of params", which makes sense for your example too in my book.

That said, `with_params` is unambiguous and we all seem to like it, so 👍 ?

**Comment by edwardloveall** [comment]
More up to @paulcsmith on that one. He thought it was too long.

**Comment by paulcsmith** [comment]
Yeah I think if it were used infrequently then with_params would be perfect, but it’s going to be used a ton and is not too tricky to learn. So I think the trade off is that it’s slightly harder to grok at first glance, but then you learn it quickly and have less typing and reading to do from then on. 

I’m asking some others for advice on this, but I think this is the direction that will result in best long term happiness. Does that make sense?

**Comment by derekprior** [comment]
`with` is crystal clear (sorry, not sorry) to me given the context

**Comment by paulcsmith** [comment]
We’re Lucky to have you’re insights and puns @derekprior
