### ISSUE TITLE
Code of Conduct, Contributing guidelines etc.

### ISSUE THREAD

**Issue by 5minpause** [luckyframework/web#172]
Hi @paulcsmith.
Is there anything planned regarding a [CoC](https://thoughtbot.com/open-source-code-of-conduct) or contributing guidelines (like https://github.com/thoughtbot/factory_bot/blob/master/CONTRIBUTING.md)?

How could I help with this? Would you rather use existing documents from other Thoughtbot projects, or would you use different ones?

**Comment by paulcsmith** [comment]
Great idea! I think we can use the same one factory_boy uses https://github.com/thoughtbot/factory_bot/blob/master/CONTRIBUTING.md except "Ruby" -> "Crystal" of course :)

If you could submit a PR for that it'd be greatly appreciated :D

**Comment by 5minpause** [comment]
will do!

**Comment by citizen428** [comment]
Regarding a code of conduct, [this](https://www.contributor-covenant.org) seems to be gaining traction, i.e. [dry-rb](http://dry-rb.org/conduct/) are using a modified version. The full text can be found [here](https://www.contributor-covenant.org/version/1/4/code-of-conduct.md)

**Comment by paulcsmith** [comment]
@citizen428 I read through your PR and I really like it. I think it could work, but I’d prefer to use the code of conduct from thoughtbot along with the contributing.me mentioned above so that ya consistent with other projects built at thoughtbot. 
I think that way people contributing to projects built at thoughtbot can become familiar with the contributing guidelines across projects

**Comment by citizen428** [comment]
@paulcsmith I see where you're coming from, I wasn't sure how much of a thoughtbot project this was. Anyway, I updated my PR to include a Markdown version of the thoughtbot CoC because I think it's good to have it as part of the repository and not only linked externally.

**Comment by paulcsmith** [comment]
Good thought. Thanks @citizen428!

I’ll leave this open for now and will close once I’ve added a contributing.md
