### ISSUE TITLE
If content-type is JSON and body is empty, use an empty hash instead of raising

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#180]
Right now if LuckyWeb::Params.get/nested/etc. is called and the content-type is JSON and the body is nil or "" then it raises because it can't parse the JSON correctly.

Instead it should check if the string is nil or empty with `.present?` and only parse if it's a valid value. If it's blank, then return an empty string or `nil` depending on if a `!` version is used

**Comment by azbshiri** [comment]
```
  private def parsed_json
    return JSON.parse("{}") if body.blank?
    @_parsed_json ||= JSON.parse(body)
  end
```

How about this?

**Comment by paulcsmith** [comment]
Thanks @azbshiri! That’s roughly what I did. I just forgot to push it up to master :facepalm: I’ll do that when I get on WiFi
