### ISSUE TITLE
Add check box helper

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#19]
Remember to use hidden field so we get the unchecked value. This will work similar to the `text_input` helpers https://github.com/luckyframework/web/blob/master/src/lucky_web/tags/input_helpers.cr

http://stackoverflow.com/questions/11550941/why-does-the-check-box-form-helper-generate-two-checkboxes-one-hidden

Also: https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/inputs/boolean_input.rb#L93

**Comment by 5minpause** [comment]
I started work on this one.

**Comment by 5minpause** [comment]
I plan to have this done by the end of the week. If you need it quicker, please feel free to implement it as well. @paulcsmith

**Comment by paulcsmith** [comment]
@5minpause I think that will be great, but I'll let you know if I need it quicker. Thanks for the update!

**Comment by 5minpause** [comment]
Alright the PR is open. I am looking very much forward to your feedback.
