### ISSUE TITLE
Undefined method 'to_param' for Int32 on action parameter

### ISSUE THREAD

**Issue by Xosmond** [luckyframework/web#191]
This code:
`redirect to: Users::Show.with(user.id)`

Generate this error:
```
20:39:42 web.1      |  expanding macro
20:39:42 web.1      |  in macro 'add_route' /Users/osmond/Developer/Crystal/lucky/my_blog/lib/lucky_web/src/lucky_web/routeable.cr:50, line 54:
20:39:42 web.1      |     1.     LuckyWeb::Router.add(:get, "/users/:id", Users::Show)
...
20:39:42 web.1      |    40.     def self.route(
20:39:42 web.1      |    41.
20:39:42 web.1      |    42.       id,
20:39:42 web.1      |    43.
20:39:42 web.1      |    44.       )
20:39:42 web.1      |    45.       path = String.build do |path|
20:39:42 web.1      |    46.
20:39:42 web.1      |    47.           path << "/"
20:39:42 web.1      |    48.
20:39:42 web.1      |    49.             path << "users"
20:39:42 web.1      |    50.
20:39:42 web.1      |    51.
20:39:42 web.1      |    52.           path << "/"
20:39:42 web.1      |    53.
20:39:42 web.1      |  > 54.             path << id.to_param
20:39:42 web.1      |    55.
20:39:42 web.1      |    56.
20:39:42 web.1      |    57.       end
undefined method 'to_param' for Int32
```

It would be better to convert to string before using  `.to_param` method, because calling `to_s` on every action is annoying.

Or I'm wrong?

**Comment by paulcsmith** [comment]
Great question. That definitely would be annoying. You can pass just `user` and then you don't need to call `to_s` though. 

Note that this will be changed in a future release. Soonish the types of params will be `User::Id` or `Article::Id` so you would need to do `user.id`. The advantage of doing it this way is that you won't ever accidentally pass the wrong thing to the `with`.

I'll close this for now though. i hope this helps!
