### ISSUE TITLE
Add module to allow printing other types in HTML text

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#192]
Right now you can only print strings to HTML. So you have to `to_s` Int32s for example.

Instead, let's do something like this:
* Add a `LuckyWeb::HtmlOutputtable` (hoping to find a better name)
* Change type restriction for HTML tags from `String` to `String | LuckyWeb::HtmlOutputtable`
* Add `LuckyWeb::HtmlOututtable` to `Int32` and `Int64`

Other types could also include the module to be allowed in HTML text, but I think that should be rarely done. Might be helpful for custom types like `Money` or `EmailAddress` though. That way you don't need to `to_s` it first

**Comment by paulcsmith** [comment]
Maybe a good name for this is `LuckyWeb::AllowedInTags`

**Comment by 5minpause** [comment]
I am working on this and have some trouble understand Crystal / getting it to work like I understand it 😏

**Comment by 5minpause** [comment]
Alright @paulcsmith I am not really sure of my changes. I am still very new to crystal and do not know whether this is all "how it's done"™️ .

Please let me know what you think.
