### ISSUE TITLE
Discuss: how to serialize JSON

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#193]
I've got a few ideas. I want to use plain classes as much as possible. I've found jbuilder to be difficult to grasp at first, and ActiveModel serializer's to be hard to extend. 

I think this could be mitigated by using mostly plain Crystal classes and a couple methods added by Lucky.

> Note that you can already send JSON with the `json` method in actions. This discussion is about how to write the guides and what extra classes/modules Lucky can provide to make things nicer to use.

I'm thinking something like this:

```crystal
# In an action
user = UserQuery.new.first
# the `json` helper calls `to_json` on the passed in object
json UserJson::One.new(user)

# or render many
json UserJson::Many.new(UserQuery.all, next_page: "/users?page=2")

# the serializer
module UserJson
  class One < LuckyWeb::Serializer
    getter user

    def initialize(@user : User)
    end

    def as_json
      {name: name, age: user.age, email: user.email}
    end

    # Customize output with regular Crystal methods
    def name
      "#{user.first_name} #{user.last_name}"
    end
  end

  class Many < LuckyWeb::Serializer
    getter users, next_page

    def initialize(@users : UserQuery, @next_page : String)
    end

    def as_json
      # You could also add additional metadata by adding new keys to this NamedTuple
      # Learning lots of DSL is not necessary
      {users: users_as_json, next_page: next_page}
    end

    private def users_as_json
      users.map { |user| One.new(user) }
    end
  end
end

class LuckyWeb::Serialize
  def to_json
    as_json.to_json
  end

  # May also have options for camelizing key names and a few other helpers
  # But overall this would be a pretty minimal API
end
```

### Pros

* Almost entirely regular Crystal
* Makes it easy to understand
* Easy to extend
* Clear how you could pass in initial data to be rendered (next page, current page, metadata, etc)

### Cons

* Wordier than options like ActiveModel Serializer
* Decent amount of typing going on.
* Might not be easy to see what's going on at a glance?

### Takeaways

I like this approach because it makes it clear how to extend things with regular Crystal methods. I think it should be fairly simple to learn. I'm not sure if the best approach is to put both the `One` and `Many` classes in one file or not, or if those are good names. 

What does everyone think?

**Comment by satb** [comment]
Isn't writing this for every model you want to serialize too verbose? Isn't there a more declarative way? Perhaps declaring something in a list what has to be serialized and any customizations that take in a lambda? Most of the times, customizations aren't required so it keeps it simple...but in case its required, maybe a lambda can be substituted. Sorry, I am not proficient enough in Crystal yet to offer a good API.

**Comment by paulcsmith** [comment]
Here is another approach that uses `needs` so that you can pass extra data to the serialize. It uses an `attributes` macro to set the fields. A bit more concise, but I think it's also still flexible

https://gist.github.com/paulcsmith/be2aba4868e5df27a7064bae0756af21

**Comment by edwardloveall** [comment]
What if you used the existing pages API? You have actions just like normal actions with `needs` and `render`, etc. Then in the view, maybe instead of inheriting from `BasePage` or whatever, you inherit from `LuckyWeb::JsonPage` or something. `render` could require some kind of json object to be returned so it's typesafe. Overrides work as normal, and everyone can use the paradigm they're used to.

**Comment by paulcsmith** [comment]
@edwardloveall Could you give an example of what you'd expect that to look like? I'm not sure I can visualize how that would work

**Comment by edwardloveall** [comment]
Yeah for sure. I'll do that tonight.

**Comment by SeanRoberts** [comment]
Verbosity is definitely my preference here if it leads to more extensibility.  I am personally not a huge fan of the `has_many` stuff in Active Model Serializers as I generally want to render different output for a list of comments underneath a user, a single comment, or a global list of comments.  

I think you're on the right track here.

**Comment by paulcsmith** [comment]
Thanks for your input @SeanRoberts!

Maybe something like this could work. Seems like a nice balance between mostly regular Crystal methods and data structures, without too much typing:

```crystal
# User has first_name, last_name, age, and email fields
# User::BaseJson sets up a default initialize that accepts a User instance
# It also sets up a getter so you can access the `user`
class User::Json < User::BaseJson
  def data
    {name: name, email: email, comments: comments}
  end
  
  def name
    "#{user.first_name} #{user.last_name}"
  end
  
  def comments
    SimpleCommentJson::Many.new(user.comments)
  end
  
  class Many
    needs count : Int32
    
    def data
      {users: users.map { |user| UserJson.new(user) }, count: count }
    end
  end
end

json UserJson::Many.new(users, count: 20)
json UserJson.new(user)
```

**Comment by SeanRoberts** [comment]
@paulcsmith That looks great to me.  If we can pass options to `UserJson.new` that we can use to conditionally render certain things I think it would be a perfect fit.  ie:

```crystal
class UserJson < User::BaseJson
  def data
    data = { name: name, email: user.email }
    data[:comments] = comments unless options.supress_comments
    data
  end
  
  def name
    "#{user.first_name} #{user.last_name}"
  end
  
  def comments
    SimpleCommentJson::Many.new(user.comments)
  end
  
  class Many
    needs count : Int32
    
    def data
      {users: users.map { |user| UserJson.new(user, suppress_comments: true) }, count: count }
    end
  end
end

json UserJson::Many.new(users, count: 20)
json UserJson.new(user)
```

Tweaking JSON endpoints to be performant has been a huge pain point for me in the past, so being able to conditionally render based on context would be nice.  A lot of the time it does make sense to create multiple serializers instead but when it's just one or two keys that causes a huge render overhead it's nice to have the option to not duplicate out a whole different serializer that's 95% similar.

**Comment by paulcsmith** [comment]
@seanroberts yep that will definitely be possible. You'd use `needs` like this:

```crystal
class UserJson < User::BaseJson
  needs supress_comments? : Bool = false # Defaults to false

  def data
    json = { name: name, email: user.email }
    json.merge({ comments: comments }) unless suppress_comments?
  end
end

json UserJson.new(user, supress_comments: true)
```

**Comment by SeanRoberts** [comment]
@paulcsmith Great, this looks like a very good balance between verbosity and extensibility.  Looking forward to trying it out!

**Comment by edwardloveall** [comment]
My idea is to serialize JSON in the same way that you "serialize" HTML for a page. I'm thinking of it just like I would think of a page displaying HTML. An action using a query to access data and a generic page class to display it:

```crystal
# /src/actions/api/users/index.cr
class Api::Users::Index < BaseAction
  action do
    render users: UserQuery.new.first
  end
end
```

```crystal
# /src/pages/api/users/index_page.cr
class Api::Users::IndexPage < JsonPage
  needs users : UserQuery

  render do
    {
      users: @users.map do |user|
        {
          name: name(user),
          age: user.age,
          email: user.email
        }
      ]
      count: @users.count
    }
  end

  private def name(user)
    "#{user.first_name} #{user.last_name}"
  end
end
```

> Note the JsonPage superclass. I would imagine that would not include the tag helpers and perhaps automatically convert whatever the output of `render` is to JSON.

That's essentially it. No explicit serializers, no One or Many classes. Everyone just uses a very similar API.

Is there some advantage to having separate serializer classes that I'm totally missing? Maybe keeping code reusable, but I can envision using components for that ([like here](https://github.com/luckyframework/web/issues/185#issuecomment-341937648))

**Comment by satb** [comment]
@edwardloveall - In my mind, I think of serializers as more general purpose. Its a centralized place to place your serialization logic. You don't have to go through the entire request lifecycle to serialize the data (with pages). You might as well stop mid way in the lifecycle and render it out if such a need arises. Such functionality is generally called serializer and its like an anchor in the mind. When someone experienced in other frameworks sees the word serializer, they almost instantly know what they are dealing with. Are serializers absolutely required? No. Can it be done in other ways? Yes, as you have shown. Can it be called something else? Yes, certainly. All of these have been crystallized into what we know as Serializers today. My 2 cents.

**Comment by edwardloveall** [comment]
Great points @satb. I didn't consider at all using serializers in a non-view context, like passing data to another API. And I agree that the word serializer invokes a certain type of functionality. Good signaling to other devs that use other frameworks can definitely help adoption.

**Comment by paulcsmith** [comment]
If anyone is interested, I've got a rough draft for a guide on "Writing JSON APIs": https://github.com/luckyframework/website/pull/81. I'd love some feedback/testers if anyone has a moment
