### ISSUE TITLE
Possible bug with the latest change to Page -> HTMLPage

### ISSUE THREAD

**Issue by ugisozols** [luckyframework/web#208]
https://gist.github.com/ugisozols/98ff736514cc0edf4e2d25ffc1c6a257

I'm completely new to Crystal and Lucky, so I might just be doing something wrong 😄

**Comment by paulcsmith** [comment]
@ugisozols Is there any more error messaging higher up? I'm curious what the initializer for the page looks like, but I think it might be higher up

**Comment by paulcsmith** [comment]
@ugisozols I found a bug that was introduced by the new layouts. I refactored the way needs works and added a failing spec for it. You should be good to go now if you `shards update` to the latest version on master 👍

**Comment by ugisozols** [comment]
It's working 👍  😃
