### ISSUE TITLE
Add an option to show timestamps on same line as status/path etc. in logger

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#210]
https://github.com/luckyframework/web/pull/207#issuecomment-343697763

This will work similarly to how we do this with the ErrorHandler: https://github.com/luckyframework/web/blob/master/src/lucky_web/error_handler.cr#L4-L6

The options should be called `show_timestamps`

* Use `Habitat.create` to create a `show_timestamps` setting.
* If that setting is true include the timestamp in the `LuckyWeb::LogHandler` output
* If false, do not include it
* See https://github.com/luckyframework/web/blob/master/spec/lucky_web/error_handling_spec.cr#L49 for an example of testing this
* You'll also need to configure the handler in spec_helper: https://github.com/luckyframework/web/blob/master/spec/spec_helper.cr#L21 similar to how the other classes/modules are configured in that file

**Comment by arr-dev** [comment]
I could try tackling this

**Comment by arr-dev** [comment]
Is there any standard format used in the framework already?
I couldn't find any. Assume `ISO_8601` should be used?

**Comment by arr-dev** [comment]
Example:

```
GET 200 /? 2017-11-13T15:12:10+0100 (372.0µs)
   ▸ Handled by Home::Index
   ▸ Rendered LuckyWeb::WelcomePage
GET 404 /favicon.ico? 2017-11-13T15:12:10+0100 (137.0µs)
```

**Comment by paulcsmith** [comment]
@arr-dev That looks great. I think ISO8601 will work well 👍
