### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/web#23]
![dark full logo](https://cloud.githubusercontent.com/assets/22394/26591075/7d3dd936-452a-11e7-8f2a-8b9ee277cf20.png)

**Comment by paulcsmith** [comment]
@stephendolan Thank you so much for asking ahead of time! I think as long as you are not using it for merchandise or implying it is officially supported by Lucky this is ok :D I would feel better if it has some glasses and said "unofficial" though, just to make it clear that we don't own it or can make changes/edit/etc.

I would love to do some LuckyCasts on the official website at some point though so maybe we can join forces later on down the road :D

**Comment by stephendolan** [comment]
@paulcsmith Awesome, and will do! Yeah, right now it's just going to be a fun project to help me learn Crystal and Lucky, but once I feel like I'm not a complete novice I'd be thrilled to help out folks reading through the main docs!
